// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/produtos": {
            "post": {
                "description": "Cria um produto no banco de dados com código, descrição e saldo inicial",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "parameters": [
                    {
                        "description": "Dados do Produto",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ProdutoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ProdutoResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ProdutoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produtos/{codigo}/debitar": {
            "post": {
                "description": "Debita a quantidade de um produto no estoque",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código do Produto",
                        "name": "codigo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quantidade a debitar",
                        "name": "quantidade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.DebitarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler.DebitarRequest": {
            "type": "object",
            "required": [
                "quantidade"
            ],
            "properties": {
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.ProdutoRequest": {
            "type": "object",
            "required": [
                "codigo",
                "descricao"
            ],
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "saldo": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.ProdutoResponse": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "mensagem": {
                    "type": "string"
                },
                "saldo": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Service Estoque API",
	Description:      "Microsserviço de controle de estoque para o teste Korp.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
