basePath: /api/v1
definitions:
  internal_handler.DebitarRequest:
    properties:
      quantidade:
        type: integer
    required:
    - quantidade
    type: object
  internal_handler.ProdutoRequest:
    properties:
      codigo:
        type: string
      descricao:
        type: string
      saldo:
        type: integer
    required:
    - codigo
    - descricao
    type: object
  internal_handler.ProdutoResponse:
    properties:
      codigo:
        type: string
      descricao:
        type: string
      mensagem:
        type: string
      saldo:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: Microsserviço de controle de estoque para o teste Korp.
  title: Service Estoque API
  version: "1.0"
paths:
  /produtos:
    post:
      consumes:
      - application/json
      description: Cria um produto no banco de dados com código, descrição e saldo
        inicial
      parameters:
      - description: Dados do Produto
        in: body
        name: produto
        required: true
        schema:
          $ref: '#/definitions/internal_handler.ProdutoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.ProdutoResponse'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_handler.ProdutoResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - produtos
  /produtos/{codigo}/debitar:
    post:
      consumes:
      - application/json
      description: Debita a quantidade de um produto no estoque
      parameters:
      - description: Código do Produto
        in: path
        name: codigo
        required: true
        type: string
      - description: Quantidade a debitar
        in: body
        name: quantidade
        required: true
        schema:
          $ref: '#/definitions/internal_handler.DebitarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - produtos
swagger: "2.0"
